added eval plugin
pyrogram/plugins pull request #1
Opened 2018-11-06 14:58 UTC by Furoin

2018-11-06 16:58 UTC, delivrance commented
Hi. Add yourself in the readme

2018-11-07 10:35 UTC, delivrance commented on plugins/eval/eval.py
> +eval_result_text = "**Eval Code:**\n```{code}```\n**Result:**\n```{result}```"
I like these to be UPPER_CASE

2018-11-07 10:36 UTC, delivrance commented on plugins/eval/eval.py
> +        m = client.send_message(message.chat.id, eval_running_text.replace('{code}', code), parse_mode="MARKDOWN")
Don't use replace, use format instead.
Also, you could just use message.reply here

2018-11-07 10:37 UTC, delivrance commented on plugins/eval/eval.py
> +            else:
This will give a wrong output in case the result equals to 0, `eval(1-1)` for example.

2018-11-07 10:37 UTC, delivrance commented on plugins/eval/eval.py
> +                                         parse_mode="MARKDOWN")
Markdown is enabled by default, there's no need for it.

2018-11-07 10:48 UTC, delivrance requested changes
There are quite a few fixes needed to make this plugin nicer. Here's how I suggest it to be instead (there's still some redundant code because of message.edit() not being available (yet), but we can add it later):

```python
from pyrogram import Client, Filters

RUNNING = "**Eval Code:**\n```{}```\n**Running...**"
ERROR = "**Eval Code:**\n```{}```\n**Error:**\n```{}```"
SUCCESS = "**Eval Code:**\n```{}```\n**Success**"
RESULT = "**Eval Code:**\n```{}```\n**Result:**\n```{}```"


@Client.on_message(Filters.command("eval", prefix="!"))
def eval_code(client, message):
    code = " ".join(message.command[1:])

    if code:
        m = message.reply(RUNNING.format(code))

        try:
            result = eval(code)
        except Exception as error:
            client.edit_message_text(
                m.chat.id,
                m.message_id,
                ERROR.format(code, error)
            )
        else:
            if result is None:
                client.edit_message_text(
                    m.chat.id,
                    m.message_id,
                    SUCCESS.format(code)
                )
            else:
                client.edit_message_text(
                    m.chat.id,
                    m.message_id,
                    RESULT.format(code, result)
                )
```

2018-11-07 11:01 UTC, delivrance commented
And here's how the plugin will look like as soon as `Message.edit()` is added. Nice and clean:

```python
from pyrogram import Client, Filters

RUNNING = "**Eval Code:**\n```{}```\n**Running...**"
ERROR = "**Eval Code:**\n```{}```\n**Error:**\n```{}```"
SUCCESS = "**Eval Code:**\n```{}```\n**Success**"
RESULT = "**Eval Code:**\n```{}```\n**Result:**\n```{}```"


@Client.on_message(Filters.command("eval", prefix="!"))
def eval_code(client, message):
    code = " ".join(message.command[1:])

    if code:
        reply = message.reply(RUNNING.format(code))

        try:
            result = eval(code)
        except Exception as error:
            reply.edit(ERROR.format(code, error))
        else:
            if result is None:
                reply.edit(SUCCESS.format(code))
            else:
                reply.edit(RESULT.format(code, result))
```

2018-11-08 06:25 UTC, Sunda001 commented
Wow

2018-11-08 20:53 UTC, merged